#!/usr/bin/perl -W

use strict;

my $log = join "", <>;
my $start = rindex $log, "#### Testing";
my $test_log = substr $log, $start;
print "[if empty, build was failed]\n\n";
print $test_log;
print "\n\nvps1.romantereshin.com\n";
