#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../../LICENSE.   #
#                                                                       #
#########################################################################

# $Id$

LIBNAME=bigarray
EXTRACFLAGS=-I../win32unix -DIN_OCAML_BIGARRAY
EXTRACAMLFLAGS=-I ../win32unix
COMPFLAGS=-warn-error A -g
COBJS=bigarray_stubs.$(O) mmap_win32.$(O)
CAMLOBJS=bigarray.cmo
CMIFILES=$(CAMLOBJS:.cmo=.mli)

include ../Makefile.nt

install::
	cp bigarray.h $(LIBDIR)/caml/bigarray.h

depend:
	gcc -MM $(CFLAGS) *.c > .depend
	../../boot/ocamlrun ../../tools/ocamldep *.mli *.ml >> .depend

include .depend
