#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../../LICENSE.   #
#                                                                       #
#########################################################################

# $Id$

include ../../config/Makefile

CC=$(BYTECC)
CFLAGS=-I../../byterun -I../win32unix -DIN_OCAML_BIGARRAY
CAMLC=../../boot/ocamlrun ../../ocamlc -I ../../stdlib -I ../win32unix
CAMLOPT=../../boot/ocamlrun ../../ocamlopt -I ../../stdlib -I ../win32unix -closed
MKLIB=../../boot/ocamlrun ../../tools/ocamlmklib
COMPFLAGS=-warn-error A -g

C_OBJS=bigarray_stubs.$(O) mmap_win32.$(O)

CAML_OBJS=bigarray.cmo

all: libbigarray.$(A) bigarray.cma

allopt: libbigarray.$(A) bigarray.cmxa

libbigarray.$(A): $(C_OBJS)
	OCAMLLIB=../../byterun $(MKLIB) -o bigarray $(C_OBJS)

bigarray.cma: $(CAML_OBJS)
	$(MKLIB) -o bigarray -ocamlc "..\\..\\boot\\ocamlrun ..\\..\\ocamlc" -linkall $(CAML_OBJS)

bigarray.cmxa: $(CAML_OBJS:.cmo=.cmx)
	$(MKLIB) -o bigarray -ocamlopt "..\\..\\boot\\ocamlrun ..\\..\\ocamlopt" -linkall $(CAML_OBJS:.cmo=.cmx)
	OCAMLLIB=../../byterun $(CAMLOPT) -shared bigarray.cmxa

install:
	cp dllbigarray.dll $(STUBLIBDIR)
	cp libbigarray.$(A) $(LIBDIR)
	cp bigarray.cmi bigarray.mli bigarray.cma $(LIBDIR)
	cp bigarray.h $(LIBDIR)/caml/bigarray.h

installopt:
	cp bigarray.$(A) $(CAML_OBJS:.cmo=.cmx) bigarray.cmxa bigarray.so $(LIBDIR)

partialclean:
	rm -f *.cm*

clean: partialclean
	rm -f *.dll *.$(A) *.$(O) *.so

.SUFFIXES: .ml .mli .cmo .cmi .cmx .$(O)

.mli.cmi:
	$(CAMLC) -c $(COMPFLAGS) $<

.ml.cmo:
	$(CAMLC) -c $(COMPFLAGS) $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

.c.$(O):
	$(BYTECC) $(BYTECCCOMPOPTS) $(CFLAGS) -c $<

depend:
	gcc -MM $(CFLAGS) *.c > .depend
	../../boot/ocamlrun ../../tools/ocamldep *.mli *.ml >> .depend

include .depend
