#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../../LICENSE.   #
#                                                                       #
#########################################################################

# $Id$

include ../../config/Makefile

# Compilation options
CC=$(BYTECC)
CFLAGS=-I../../byterun -I../unix
CAMLC=../../boot/ocamlrun ../../ocamlc -I ../../stdlib
CAMLOPT=../../boot/ocamlrun ../../ocamlopt -I ../../stdlib -closed
MKLIB=../../boot/ocamlrun ../../tools/ocamlmklib
COMPFLAGS=-warn-error A -g

# Files in this directory
WIN_FILES = accept.c bind.c channels.c close.c \
  close_on.c connect.c createprocess.c dup.c dup2.c errmsg.c \
  getpeername.c getpid.c getsockname.c gettimeofday.c \
  link.c listen.c lockf.c lseek.c nonblock.c \
  mkdir.c open.c pipe.c read.c rename.c \
  select.c sendrecv.c \
  shutdown.c sleep.c socket.c sockopt.c startup.c stat.c \
  system.c unixsupport.c windir.c winwait.c write.c

# Files from the ../unix directory
UNIX_FILES = access.c addrofstr.c chdir.c chmod.c cst2constr.c \
  cstringv.c envir.c execv.c execve.c execvp.c \
  exit.c getcwd.c gethost.c gethostname.c getproto.c \
  getserv.c gmtime.c putenv.c rmdir.c \
  socketaddr.c strofaddr.c time.c unlink.c utimes.c

ALL_FILES=$(WIN_FILES) $(UNIX_FILES)

OBJS=$(ALL_FILES:.c=.$(O))

LIBS=$(call SYSLIB,wsock32)

MLOBJS=unix.cmo unixLabels.cmo

UNIX_CAML_FILES = unix.mli unixLabels.mli unixLabels.ml

all: libunix.$(A) unix.cma

allopt: libunix.$(A) unix.cmxa

libunix.$(A): $(OBJS)
	OCAMLLIB=../../byterun $(MKLIB) -o unix $(OBJS) -ldopt $(LIBS)

unix.cma: $(MLOBJS)
	$(MKLIB) -o unix -ocamlc "..\\..\\boot\\ocamlrun ..\\..\\ocamlc" -linkall $(MLOBJS)

unix.cmxa: $(MLOBJS:.cmo=.cmx)
	$(MKLIB) -o unix -ocamlopt "..\\..\\boot\\ocamlrun ..\\..\\ocamlopt" -linkall $(MLOBJS:.cmo=.cmx) -cclib $(LIBS)
	OCAMLLIB=../../byterun $(CAMLOPT) -shared unix.cmxa

partialclean:
	rm -f *.cm*

clean: partialclean
	rm -f *.$(A) *.dll *.$(O) *.so
	rm -f $(UNIX_FILES) $(UNIX_CAML_FILES)

install:
	cp dllunix.dll $(STUBLIBDIR)/dllunix.dll
	cp libunix.$(A) $(LIBDIR)/libunix.$(A)
	cp unix.cma $(MLOBJS:.cmo=.cmi) $(MLOBJS:.cmo=.mli) $(LIBDIR)
	cp unixsupport.h $(LIBDIR)/caml

installopt:
	cp $(MLOBJS:.cmo=.cmx) unix.cmxa unix.$(A) unix.so $(LIBDIR)

$(UNIX_FILES) $(UNIX_CAML_FILES): %: ../unix/%
	cp ../unix/$* $*

.SUFFIXES: .ml .mli .cmo .cmi .cmx .$(O) .c

.mli.cmi:
	$(CAMLC) -c $(COMPFLAGS) $<

.ml.cmo:
	$(CAMLC) -c $(COMPFLAGS) -nolabels $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) -nolabels $<

.c.$(O):
	$(BYTECC) $(BYTECCCOMPOPTS) $(CFLAGS) -c $<

depend:

$(OBJS): unixsupport.h

include .depend
