#!/bin/bash

env_err_message="Environment is not correct. Try edit setenv.sh properly and do '. setenv.sh' first. If setenv.sh doesn't exist copy it from _setenv.sh"

if [ -z "$OCAML_ROOT" ] \
  || [ -z "$LLVM_ROOT" ] \
  || [ -z "$LLVM_SRC_ROOT" ] \
  || [ -z "$LLVM_OBJ_ROOT" ]
then
  echo "One of user defined variables is empty: " $env_err_message
  exit 1
fi

if [ "$1" = "--before-install" ]; then
  exit 0
fi


if [ ! -f "$JBLABGC" ]; then
  echo "GC-plugin not found (path: '$JBLABGC'): " $env_err_message
  exit 2
fi

if [ ! -f "$OCAML_ROOT/bin/scripts/llb" ]; then
  echo "llb-script not found (path: $OCAML_ROOT/bin/scripts/llb): " $env_err_message
  exit 4
fi

if [ ! -f "$LLVM_ROOT/bin/llc" ]; then
  echo "llc not found (path: $LLVM_ROOT/bin/llc): " $env_err_message
  exit 8
fi
