#!/bin/bash

if [ -z "$1" ]
then
  echo "Usage: `basename $0` test-name"
  exit 1
fi

if [ "$1" == "-" ]
then
  test_name_arg=`basename $PWD`
else
  test_name_arg="$1"
fi
test_name=${test_name_arg%.ml}
source_name="$test_name.ml"

pull_runtime
if [ ! -e "$source_name" ]
then
  extract_externals runtime.c > $source_name
fi

if [ ! -e Makefile ]
then
  makefile_name=Makefile
  program_name="$test_name"
else
  makefile_name=Makefile.second
  program_name="program"
  aux_opts="-DNDEBUG -Wno-unused-variable -Wno-unused-function"
fi

cat > "$makefile_name" <<EOF
PROGRAM = $program_name
OBJECTS = $test_name.o runtime.o

override CFLAGS := -std=c99 -g -Wall -pedantic $aux_opts \$(CFLAGS)

.SUFFIXES: .ml

.ml.o:
	llb $< -load=\$(JBLABGC)

\$(PROGRAM): \$(OBJECTS)
	\$(CC) \$^ -o \$@

clean:
	rm -f *.o
	rm -f *.cm[ixo]
	rm -f *.o.dump
	rm -f *.o.symb
	rm -f out
	rm -f *.cmm

distclean:
	rm -f *.o
	rm -f *.cm[ix]
	rm -f *.ll
	rm -f *.[sS]
	rm -f \$(PROGRAM)
	rm -f *.o.dump
	rm -f *.o.symb
	rm -f out
	rm -f output.txt
	rm -f right_output.txt
	rm -f test_input.txt
	rm -f stderr.txt
	rm -f out
	rm -f *.cmm
EOF
