TARGET=cmt2annot
MLIS=
MLS=cmt2annot.ml
CMAS= unix.cma toplevellib.cma
INCLUDES= \
 -I ../ocaml-binary-annot/typing \
 -I ../ocaml-binary-annot/parsing \
 -I ../ocaml-binary-annot/utils \

OFLAGS=-g -annot

include Makefile.rules
