#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../LICENSE.      #
#                                                                       #
#########################################################################

# $Id$

include ../config/Makefile

CC=$(NATIVECC)
CFLAGS=-I../byterun -DIN_OCAMLRUN -DNATIVE_CODE -DTARGET_$(ARCH) -DSYS_$(SYSTEM) $(NATIVECCCOMPOPTS)

COBJS=startup.$(O) main.$(O) fail.$(O) roots.$(O) signals.$(O) \
  misc.$(O) freelist.$(O) major_gc.$(O) minor_gc.$(O) memory.$(O) alloc.$(O) \
  compare.$(O) ints.$(O) floats.$(O) str.$(O) array.$(O) io.$(O) extern.$(O) \
  intern.$(O) hash.$(O) sys.$(O) parsing.$(O) gc_ctrl.$(O) terminfo.$(O) \
  md5.$(O) obj.$(O) lexing.$(O) win32.$(O) printexc.$(O) callback.$(O) \
  weak.$(O) compact.$(O) finalise.$(O) custom.$(O) globroots.$(O) \
  backtrace.$(O) natdynlink.$(O) exports.$(O) prims.$(O)

LINKEDFILES=misc.c freelist.c major_gc.c minor_gc.c memory.c alloc.c array.c \
  compare.c ints.c floats.c str.c io.c extern.c intern.c hash.c sys.c \
  parsing.c gc_ctrl.c terminfo.c md5.c obj.c lexing.c printexc.c callback.c \
  weak.c compact.c meta.c finalise.c custom.c main.c globroots.c \
  dynlink.c exports.c

PRIMS=alloc.c array.c compare.c extern.c floats.c gc_ctrl.c hash.c \
  intern.c ints.c io.c lexing.c md5.c meta.c obj.c parsing.c \
  str.c sys.c terminfo.c weak.c

ifeq ($(TOOLCHAIN),mingw)
ASMOBJS=$(ARCH).o
else
ASMOBJS=$(ARCH)nt.obj
endif

OBJS=$(COBJS) $(ASMOBJS)

all: libasmrun.$(A)

primitives : $(PRIMS)
	$(CPP) $(CFLAGS) -DCOMPUTE_EXPORTS $(PRIMS) | \
	sed -n -e "s/CAMLprim value \([a-z0-9_][a-z0-9_]*\).*/\1/p" \
	    > primitives

prims.c : primitives
	(echo '#include "mlvalues.h"'; \
	 echo '#include "prims.h"'; \
	 sed -e 's/.*/extern value &();/' primitives; \
	 echo 'c_primitive caml_builtin_cprim[] = {'; \
	 sed -e 's/.*/	&,/' primitives; \
	 echo '	 0 };'; \
	 echo 'char * caml_names_of_builtin_cprim[] = {'; \
	 sed -e 's/.*/	"&",/' primitives; \
	 echo '	 0 };') > prims.c

libasmrun.$(A): $(OBJS)
	$(call MKLIB,libasmrun.$(A), $(OBJS))

i386nt.obj: i386nt.asm
	ml /nologo /coff /Cp /c /Foi386nt.obj i386nt.asm

amd64nt.obj: amd64nt.asm
	ml64 /nologo /Cp /c /Foamd64nt.obj amd64nt.asm

i386.o: i386.S
	$(CC) -c -DSYS_$(SYSTEM) i386.S

install:
	cp libasmrun.$(A) $(LIBDIR)

$(LINKEDFILES): %.c: ../byterun/%.c
	cp ../byterun/$*.c $*.c

# Need special compilation rule so as not to do -I../byterun
win32.$(O): ../byterun/win32.c
	$(CC) -c $(NATIVECCCOMPOPTS) -DIN_OCAMLRUN -DNATIVE_CODE ../byterun/win32.c

.SUFFIXES: .c .$(O)

.c.$(O):
	$(CC) $(CFLAGS) -c $<

clean::
	rm -f $(LINKEDFILES)

clean::
	rm -f *.$(O) *.$(A) *~ prims.c

.depend.nt:
	sed -e 's/\.o/.$(O)/g' .depend > .depend.nt

include .depend.nt
